export const applyCmsDefaults = {
  en: {
    "ui.bookSession": "Book a Session",
    "ui.selectDate": "Select a Date",
    "ui.noDates": "No available dates at the moment. Please check back later.",
    "ui.availableTimes": "Available Times",
    "ui.noSlots": "No available slots for this date.",
    "ui.yourDetails": "Your Details",
    "ui.fullName": "Full Name",
    "ui.email": "Email Address",
    "ui.phone": "Phone Number",
    "ui.payment": "Payment",
    "ui.service": "Service",
    "ui.dateTime": "Date & Time",
    "ui.fullPayment": "Full Payment",
    "ui.deposit": "Deposit",
    "ui.remaining": "(remaining due before session)",
    "ui.amountDue": "Amount Due Now",
    "ui.paymentDetails": "Payment Details (Required)",
    "ui.platform": "Payment Platform",
    "ui.billingName": "Billing Full Name",
    "ui.billingCountry": "Billing Country",
    "ui.terms": "I confirm my payment and booking details are correct.",
    "ui.paymentAfter": "Payment is completed through your selected platform link after booking confirmation.",
    "ui.confirmed": "Booking Confirmed",
    "ui.date": "Date",
    "ui.time": "Time",
    "ui.confirmationEmail": "A confirmation email will be sent to",
    "ui.back": "BACK",
    "ui.continue": "CONTINUE",
    "ui.confirmBooking": "CONFIRM BOOKING",
    "ui.processing": "PROCESSING...",
    "steps.0": "Date & Time",
    "steps.1": "Your Details",
    "steps.2": "Payment",
    "steps.3": "Confirmed",
    "form.eyebrow": "Get Started",
    "form.titleApply": "Apply / ",
    "form.titleBook": "Book",
    "form.subtitleApply": "Tell us about your advisory needs. We review every application personally.",
    "form.subtitleBook": "Complete the form below and we'll send you a booking confirmation.",
    "form.fullName": "Full Name",
    "form.email": "Email Address",
    "form.message": "Message",
    "form.submit": "SUBMIT APPLICATION",
    "form.sending": "SENDING...",
    "form.successToast": "Your inquiry has been received. We'll be in touch shortly.",
    "ui.selectDateError": "Please select a date and time slot.",
    "ui.fillFieldsError": "Please fill in all fields.",
    "ui.paymentFieldsError": "Please complete all required payment fields.",
    "ui.bookingConfirmed": "Booking confirmed!",
    "ui.bookingFailed": "Unable to confirm booking. Please try a different time slot.",
    "ui.loadDatesError": "Unable to load available dates.",
    "ui.loadSlotsError": "Unable to load available time slots.",
    "payment.optionPayLink": "Pay with Link",
    "payment.optionStripe": "Stripe",
    "payment.optionBank": "Bank Transfer",
    "ui.depositSummary": "Deposit ({pct}%)",
    "ui.fullSummary": "Full",
  },
  bg: {
    "ui.bookSession": "Резервирай Сесия",
    "ui.selectDate": "Изберете дата",
    "ui.noDates": "В момента няма свободни дати. Моля, опитайте по-късно.",
    "ui.availableTimes": "Свободни часове",
    "ui.noSlots": "Няма свободни часове за тази дата.",
    "ui.yourDetails": "Вашите Данни",
    "ui.fullName": "Име и Фамилия",
    "ui.email": "Имейл Адрес",
    "ui.phone": "Телефон",
    "ui.payment": "Плащане",
    "ui.service": "Услуга",
    "ui.dateTime": "Дата и Час",
    "ui.fullPayment": "Пълно плащане",
    "ui.deposit": "Депозит",
    "ui.remaining": "(остатъкът се доплаща преди сесията)",
    "ui.amountDue": "Сума за плащане сега",
    "ui.paymentDetails": "Данни за Плащане (Задължителни)",
    "ui.platform": "Платформа за плащане",
    "ui.billingName": "Име за фактура",
    "ui.billingCountry": "Държава за фактура",
    "ui.terms": "Потвърждавам, че данните за плащане и резервация са коректни.",
    "ui.paymentAfter": "Плащането се извършва чрез избраната от вас платежна връзка след потвърждение.",
    "ui.confirmed": "Резервацията е Потвърдена",
    "ui.date": "Дата",
    "ui.time": "Час",
    "ui.confirmationEmail": "Имейл потвърждение ще бъде изпратено до",
    "ui.back": "НАЗАД",
    "ui.continue": "ПРОДЪЛЖИ",
    "ui.confirmBooking": "ПОТВЪРДИ РЕЗЕРВАЦИЯТА",
    "ui.processing": "ОБРАБОТВАМЕ...",
    "steps.0": "Дата и Час",
    "steps.1": "Вашите Данни",
    "steps.2": "Плащане",
    "steps.3": "Потвърдено",
    "form.eyebrow": "Започнете",
    "form.titleApply": "Кандидатствай / ",
    "form.titleBook": "Резервирай",
    "form.subtitleApply": "Разкажете ни за вашите консултантски нужди. Преглеждаме всяка заявка лично.",
    "form.subtitleBook": "Попълнете формата и ще ви изпратим потвърждение за резервация.",
    "form.fullName": "Име и Фамилия",
    "form.email": "Имейл Адрес",
    "form.message": "Съобщение",
    "form.submit": "ИЗПРАТИ ЗАЯВКА",
    "form.sending": "ИЗПРАЩАНЕ...",
    "form.successToast": "Вашата заявка е получена. Ще се свържем с вас скоро.",
    "ui.selectDateError": "Моля, изберете дата и час.",
    "ui.fillFieldsError": "Моля, попълнете всички полета.",
    "ui.paymentFieldsError": "Моля, попълнете всички задължителни полета за плащане.",
    "ui.bookingConfirmed": "Резервацията е потвърдена!",
    "ui.bookingFailed": "Неуспешно потвърждение. Моля, опитайте с друг свободен час.",
    "ui.loadDatesError": "Неуспешно зареждане на дати.",
    "ui.loadSlotsError": "Неуспешно зареждане на часове.",
    "payment.optionPayLink": "Плащане с връзка",
    "payment.optionStripe": "Stripe",
    "payment.optionBank": "Банков превод",
    "ui.depositSummary": "Депозит ({pct}%)",
    "ui.fullSummary": "Пълно",
  },
} as const;
